export const ADD_TOKEN = 'ADD_TOKEN';

export const DELETE_TOKEN = 'DELETE_TOKEN';

export const ADD_TICKET = 'ADD_TICKET';

export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';

export const ADD_TICKET_FAILED = 'ADD_TICKET_FAILED';

export const REFRESH_EVENT_LIST = 'REFRESH_EVENT_LIST';

export const REFRESH_EVENT_LIST_SUCCESS = 'REFRESH_EVENT_LIST_SUCCESS';

export const REFRESH_EVENT_LIST_FAILED = 'REFRESH_EVENT_LIST_FAILED';

export const REFRESH_LOG_LIST = 'REFRESH_LOG_LIST';

export const REFRESH_LOG_LIST_SUCCESS = 'REFRESH_LOG_LIST_SUCCESS';

export const REFRESH_LOG_LIST_FAILED = 'REFRESH_LOG_LIST_FAILED';

export const ADD_LOG = 'ADD_LOG';

export const REMOVE_FAILED_TICKET = 'REMOVE_FAILED_TICKET';

export const DELETE_ALL_LOGS = 'DELETE_ALL_LOGS';

export const DELETE_ALL_PENDING_TICKETS = 'DELETE_ALL_PENDING_TICKETS';